DROP TABLE IF EXISTS Queue;

CREATE TABLE Queue (
  q_id INTEGER PRIMARY KEY AUTOINCREMENT,
  v_path TEXT NOT NULL,
  b_path TEXT NOT NULL,
  nb_path TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);