DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS video;
DROP TABLE IF EXISTS folder;

CREATE TABLE user (
  u_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  v_num INTEGER NOT NULL,
  f_num INTEGER NOT NULL,
  sticker BLOB
);

CREATE TABLE video (
  v_id INTEGER PRIMARY KEY AUTOINCREMENT,
  v_name TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  folder_name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE folder (
  f_id INTEGER PRIMARY KEY AUTOINCREMENT,
  f_name TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (id)
);