DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS video;
DROP TABLE IF EXISTS newbackground;

CREATE TABLE user (
  u_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  v_num INTEGER NOT NULL,
  f_num INTEGER NOT NULL,
  sticker BLOB
);

CREATE TABLE video (
  v_id INTEGER PRIMARY KEY AUTOINCREMENT,
  v_name TEXT NOT NULL,
  vsa_name TEXT NOT NULL,
  b_name TEXT NOT NULL,
  bsa_name TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  nb_name TEXT DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (u_id)
);

CREATE TABLE newbackground (
  nb_id INTEGER PRIMARY KEY AUTOINCREMENT,
  nb_name TEXT NOT NULL,
  nbsa_name TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (u_id)
);